### ISSUE TITLE
Users can create their own  TeamRadio station

### ISSUE THREAD

**Issue by mgm-sfrank** [mgm-interns/team-radio#2]
As a user who wants to set up a TeamRadio station for their team. I want to give a name to my TeamRadio station and share the station with my team members

*Acceptance criteria*
* On the TeamRadio home page, a station name can be entered
* I will be taken to the new team's TeamRadio station, where the station name is displayed. The URL can be copied and shared with others, who will also see the TeamRadio station whenever they follow the link
* I can't create a TeamRadio station if the station name is empty (nothing or just whitespaces) or is already in use

**Comment by ezellbuoee** [comment]
Display error message when channel already exist.
Step to validate :
1. Add a channel with any name of choice e.g "Eze Channel"
2. Navigate back to the home page and add a channel with the same name 

Expected result : Error message

Actual result : Nothing happens

Note : its very important for **_End Users_** to know whats happening in the system so that they don't assume the application is broken
