### ISSUE TITLE
A user score is recorded per station

### ISSUE THREAD

**Issue by mgm-sfrank** [mgm-interns/team-radio#8]
As a registered user, I want to have a personal score, which gets better with every activity. Like in a video game. Achievements!

As a TeamRadio project member, I want to have means to encourage registered users to be active and use many features of the application. I want TeamRadio to reward desired behaviour

*Acceptance criteria*
* In a user profile, for  each TeamRadio station I have used, I can see how many songs I have added
* For each team radio page, I see an overall score:
  * Each upvoted song gives points
  * Each downvoted song reduces points
  * The first songs give more points than songs added later
  * The score will never be negative

**Comment by chienthangplus** [comment]
I think "Each played song gives points" is not good. Because users will get so much points by adding many short songs (e.g. duration 1-20s).
The better if the points based on number of upvotes and downvotes. And "The first songs give more points than songs added later" also is unnecessary.

**Comment by baonguyendang** [comment]
I have some suggestion for the rule:

+ How to get point of station score? You can get point from: 
-	Like on your songs :  Each like on your song which you added, you get 1 point . Remember you cannot like your song. When you like a song (not yours) you spend 1 point. When your point equal zero, you cannot like song. You can like more than 1 times. It help the song you like was played more soon.
-	Adding your song: For each song you add you get 1 point, each your song was skipped you lose 1 point. When your point is -1. You need to wait a minute to continue add new song and then your point reset to zero.

+ What can you do with your point? 
-	You can like for the song you like to  make it be play soon, because the song in top of like  is played first.

**Comment by baonguyendang** [comment]
"For each song you add you get 1 point," => the duration of each song must greater than 1 minute. We don't want anybody try to spam.
